import { escapeHtml } from "../utils.js";

function buildReport(response){
 const dashboard=response?.dashboard_v2||response?.dash_v1||{},header=dashboard.header||{},referral=dashboard.referral||{},summary=dashboard.summary||{},level=dashboard.level||{},rainbow=dashboard.nutrition_rainbow||{},share=dashboard.share||{},actions=response?.actions||{};const progress=Math.max(0,Math.min(level.weekly_adherence_percent||0,100));const categories=Array.isArray(rainbow.groups)?rainbow.groups:[];const categoriesHtml=categories.map(c=>`<div class="post-report-category"><span class="post-report-category-emoji">${escapeHtml(c.emoji||"")}</span><span>${escapeHtml(c.label||"")}</span></div>`).join("");const referralUrl=share.message?`https://wa.me/?text=${encodeURIComponent(share.message)}`:"";
 return `<section class="post-report"><section class="post-report-heading"><div class="post-report-tag">TU SEMANA FRUTI</div><h1 class="post-report-title">${escapeHtml(header.title||"Tu semana saludable 🎉")}</h1><p class="post-report-subtitle">${escapeHtml(header.subtitle||"")}</p></section><section class="post-report-card"><div class="post-report-label">ESTA SEMANA CUBRÍS</div><div class="post-report-main-value">${escapeHtml(summary.main_label||"")}</div>${summary.subtitle?`<div class="post-report-muted">${escapeHtml(summary.subtitle)}</div>`:""}</section><section class="post-report-card"><div class="post-report-label">TU NIVEL FRUTI</div><div class="post-report-level-row"><div class="post-report-level-icon">🌱</div><div><div class="post-report-level-name">${escapeHtml((level.status||"").replace(/[^\p{L}\p{N}\s]/gu,"").trim())}</div><div class="post-report-level-subtitle">${escapeHtml(level.status_label||"")}</div></div></div><div class="post-report-progress"><div class="post-report-progress-fill" style="width:${progress}%"></div></div></section><section class="post-report-card"><div class="post-report-rainbow-head"><div class="post-report-rainbow-icon">🌈</div><div><h2 class="post-report-card-title">${escapeHtml(rainbow.title||"Tu arcoíris nutricional")}</h2><p class="post-report-card-subtitle">${rainbow.groups_covered&&rainbow.groups_target?escapeHtml(`${rainbow.groups_covered} de ${rainbow.groups_target} grupos nutricionales cubiertos`):"Sumaste variedad en tu pedido de esta semana"}</p></div></div><div class="post-report-categories">${categoriesHtml}</div></section>${(referral.message||referralUrl)?`<section class="post-report-invite-card"><div class="post-report-invite-label">REGALÁ SALUD</div>${referral.message?`<p class="post-report-invite-text">${escapeHtml(referral.message)}</p>`:""}${referralUrl?`<a href="${escapeHtml(referralUrl)}" class="post-report-invite-btn">Invitar a un amigo</a>`:""}</section>`:""}<section class="post-report-actions">${actions.historical_report_url?`<a href="${escapeHtml(actions.historical_report_url)}" class="post-report-action-primary">Ver historial</a>`:""}${actions.whatsapp_return_url?`<a href="${escapeHtml(actions.whatsapp_return_url)}" class="post-report-action-secondary">Volver a WhatsApp</a>`:""}</section></section>`;
}

export function renderOrderDashboard(response,{headerEl,pedidoSummaryEl,orderListEl,orderTotal,formatTotal,deliverySchedule=[],deliveryAddress={}}){
 headerEl.style.display="none";pedidoSummaryEl.innerHTML="";const schedule=deliverySchedule[0];const scheduleText=schedule?[schedule.day,schedule.window].filter(Boolean).join(" · "):"Coordinamos el horario con vos";const address=[deliveryAddress.address_line1,deliveryAddress.address_line2,deliveryAddress.city].filter(Boolean).join(" · ");
 orderListEl.innerHTML=`<section class="order-confirmation"><div class="confirmation-check">✓</div><div class="confirmation-tag">PEDIDO CONFIRMADO</div><h1>Listo. Tu semana FRUTI está en marcha.</h1><div class="confirmation-card"><div class="confirmation-row"><span>Total</span><strong>${orderTotal!==null?formatTotal(orderTotal):"Confirmado"}</strong></div><div class="confirmation-row"><span>Entrega</span><strong>${escapeHtml(scheduleText)}</strong></div>${address?`<div class="confirmation-row"><span>Dirección</span><strong>${escapeHtml(address)}</strong></div>`:""}</div><button id="showFrutiWeek" class="confirmation-primary">Ver mi semana FRUTI</button><p class="confirmation-note">Te avisamos por WhatsApp si necesitamos coordinar algún detalle de la entrega.</p></section>`;
 document.getElementById("showFrutiWeek")?.addEventListener("click",()=>{orderListEl.innerHTML=buildReport(response);window.scrollTo({top:0,behavior:"smooth"});});
}