import { validateSessionToken } from "./session.js";
import { extraToOrderItem,quantityStep,roundOrderQuantity,basketEstimatedTotal,formatARS } from "./order/model.js";
import { loadInitialOrderData } from "./order/load.js";
import { renderExtras as renderExtrasView,renderOrder as renderOrderView,renderPedidoSummary as renderPedidoSummaryView } from "./order/render.js";
import { initManualSearch } from "./order/search.js";
import { submitOrderFlow } from "./order/submit.js";
const params=new URLSearchParams(window.location.search),token=params.get("t");let householdId=null,orderState=[],extraProducts=[],reasoningSummary="",deliveryChoice=null;
const $=id=>document.getElementById(id),statusEl=$("status"),orderListEl=$("orderList"),pedidoSummaryEl=$("pedidoSummary"),extrasEl=$("extras"),extrasBlockEl=$("extrasBlock"),manualSearchBlockEl=$("manualSearchBlock"),manualSearchToggleEl=$("manualSearchToggle"),manualSearchPanelEl=$("manualSearchPanel"),manualSearchInputEl=$("manualSearchInput"),manualSearchStatusEl=$("manualSearchStatus"),manualSearchResultsEl=$("manualSearchResults"),submitBtn=$("submitBtn"),submitTotalEl=$("submitTotal"),headerEl=$("header"),pedidoLoadingEl=$("pedidoLoading"),reportLoadingEl=$("reportLoading"),reportLoadingTitleEl=$("reportLoadingTitle"),deliveryOptionsEl=$("orderDeliveryOptions"),deliveryPickerEl=$("deliveryPicker"),deliveryDateWrapEl=$("deliveryDateWrap"),deliveryDateEl=$("deliveryDate"),deliveryWindowEl=$("deliveryWindow"),deliverySummaryEl=$("deliveryChoiceSummary");
function localISO(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`;}
function addDays(n){const d=new Date();d.setDate(d.getDate()+n);return localISO(d);}
function setStatus(m,t=""){statusEl.textContent=m||"";statusEl.className="status";if(t)statusEl.classList.add(t);}
function renderStickyTotal(){const t=basketEstimatedTotal(orderState);submitTotalEl.textContent=t!==null?formatARS(t):"";}
function renderPedidoSummary(){renderPedidoSummaryView({orderState,pedidoSummaryEl,reasoningSummary});renderStickyTotal();}function renderOrder(){renderOrderView({orderState,orderListEl});}function renderExtras(){renderExtrasView({extraProducts,orderState,extrasEl});}
function updateDeliveryChoice(date,window,label){deliveryChoice={date,window};deliverySummaryEl.textContent=`${label} · ${window.replace("-","–")} h`;submitBtn.disabled=false;document.querySelectorAll(".order-delivery-option").forEach(b=>b.classList.toggle("selected",b.dataset.deliveryDay===deliveryChoice.kind));}
function chooseDay(kind){deliveryChoice={kind,date:kind==="today"?addDays(0):kind==="tomorrow"?addDays(1):deliveryDateEl.value,window:deliveryWindowEl.value};deliveryPickerEl.hidden=false;deliveryDateWrapEl.hidden=kind!=="other";if(kind==="other"){deliveryDateEl.min=addDays(2);if(!deliveryDateEl.value)deliveryDateEl.value=addDays(2);deliveryChoice.date=deliveryDateEl.value;}updateDeliveryChoice(deliveryChoice.date,deliveryChoice.window,kind==="today"?"Hoy":kind==="tomorrow"?"Mañana":"Otro día");deliveryChoice.kind=kind;document.querySelectorAll(".order-delivery-option").forEach(b=>b.classList.toggle("selected",b.dataset.deliveryDay===kind));}
deliveryOptionsEl?.addEventListener("click",e=>{const b=e.target.closest(".order-delivery-option");if(b)chooseDay(b.dataset.deliveryDay);});deliveryWindowEl?.addEventListener("change",()=>{if(deliveryChoice)chooseDay(deliveryChoice.kind);});deliveryDateEl?.addEventListener("change",()=>{if(deliveryChoice?.kind==="other")chooseDay("other");});
async function resolveSessionFromToken(){if(householdId)return;const d=await validateSessionToken(token);householdId=d.household_id;}
async function loadInitialOrder(){try{const x=await loadInitialOrderData(householdId);orderState=x.orderState;extraProducts=x.extraProducts;reasoningSummary=x.reasoningSummary||"";renderPedidoSummary();renderOrder();renderExtras();setStatus("");}catch(e){console.error(e);setStatus("Error cargando pedido","error");}}
orderListEl.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;const di=b.dataset.detailToggle;if(di!==undefined){const d=orderListEl.querySelector(`[data-detail="${di}"]`);if(!d)return;const o=d.hidden;d.hidden=!o;b.innerHTML=o?`Ocultar detalle <span>⌃</span>`:`Ver detalle <span>⌄</span>`;return;}const i=Number(b.dataset.index),a=b.dataset.action;if(isNaN(i)||!orderState[i])return;const item=orderState[i],step=quantityStep(item);if(a==="plus")item.qty=roundOrderQuantity(Number(item.qty)+step,item.unit,item.unit_label);if(a==="minus"){const n=Number(item.qty)-step;if(n<=0){if(confirm("¿Eliminar este producto del pedido?"))orderState.splice(i,1);}else item.qty=roundOrderQuantity(n,item.unit,item.unit_label);}renderPedidoSummary();renderOrder();});
extrasEl.addEventListener("click",e=>{const b=e.target.closest("button"),pid=b?.dataset.add;if(!pid)return;const x=extraProducts.find(i=>(i.product||i).product_id===pid),item=extraToOrderItem(x);if(item)orderState.push(item);renderPedidoSummary();renderOrder();renderExtras();});
initManualSearch({getHouseholdId:()=>householdId,getOrderState:()=>orderState,addOrderItem:i=>orderState.push(i),renderOrder:()=>{renderPedidoSummary();renderOrder();},renderExtras,manualSearchToggleEl,manualSearchPanelEl,manualSearchInputEl,manualSearchStatusEl,manualSearchResultsEl});
submitBtn.addEventListener("click",()=>submitOrderFlow({householdId,orderState,deliveryChoice,setStatus,submitBtn,reportLoadingEl,reportLoadingTitleEl,orderListEl,extrasBlockEl,manualSearchBlockEl,headerEl,pedidoSummaryEl}));
(async()=>{try{await resolveSessionFromToken();if(!householdId){setStatus("Abrí este link desde WhatsApp con una sesión válida.","error");return;}await loadInitialOrder();setTimeout(()=>pedidoLoadingEl?.classList.add("hidden"),300);}catch(e){console.error(e);pedidoLoadingEl?.classList.add("hidden");setStatus("No se pudo validar la sesión del pedido.","error");}})();